version: '2'
services:
  combinedserver:
    extends:
      file: docker-compose.base.yml
      service: interfaceserver
    volumes:
      - .:/scintilla_api
    environment:
      - APP_ENV=DEVELOPMENT_DOCKER
      - DJANGO_SECRET_KEY
    depends_on:
      - database
      - redis
    command: /scintilla_api/entrypoint-combinedserver.sh
    restart: always
    links:
      - database:database
    #  - rabbitmq:rabbit
      - redis:redis
  database:
    extends:
      file: docker-compose.base.yml
      service: database
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
  #rabbitmq:
  #  extends:
  #    file: docker-compose.base.yml
  #    service: rabbitmq
  #celery:
  #  extends:
  #    file: docker-compose.base.yml
  #    service: celery
  #  links:
  #    - database:database
     # - rabbitmq:rabbit
  #    - redis:redis
    #command: sysctl vm.overcommit_memory=1
    #command: echo never > /sys/kernel/mm/transparent_hugepage/enabled
