version: '2'
services:
  interfaceserver:
    build: .
    command: /scintilla_api/entrypoint-interface.sh
    user: scintilla_api
    working_dir: /scintilla_api
    ports:
      - 8000:8000
    environment:
      - DJANGO_SECRET_KEY
  workerserver:
    build: .
    user: scintilla_api
    working_dir: /scintilla_api
    command: /scintilla_api/entrypoint-worker.sh
    environment:
      - DJANGO_SECRET_KEY
  database:
    image: postgres:9.5
  redis:
    image: redis:3.0-alpine
  #rabbitmq:
  #  image: tutum/rabbitmq
  #  environment:
  #    - RABBITMQ_PASS=password
  #  ports:
  #    - "5672:5672"  # we forward this port because it's useful for debugging
  #    - "15672:15672"  # here, we can access rabbitmq management plugin
  celery:
    build: .
    user: scintilla_api
    command: /scintilla_api/entrypoint-celery.sh
    volumes:
      - .:/scintilla_api