# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 19:37
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models
import sensors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('api_key', accounts.models.ApiField(blank=True, db_index=True, default=None, max_length=256, null=True)),
                ('sensor', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Ozone'), (2, 'PM2.5'), (3, 'PM10'), (4, 'CO'), (5, 'SO2'), (6, 'NO2')], db_index=True, default=0, null=True)),
                ('unit', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'PPM'), (2, 'PPB'), (3, 'UG_M3'), (4, 'DEGREES_F'), (5, 'DEGREES_C')], default=0, null=True)),
                ('average_over_hours', models.IntegerField(default=0, help_text='If the value is an average reading over time, how many hours is the average taken over? If it is not an average, the average_over_hours = 0')),
                ('value', sensors.models.DataField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('longitude', sensors.models.GeoCoordinateField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('latitude', sensors.models.GeoCoordinateField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('temperature', sensors.models.DataField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('humidity', sensors.models.DataField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('date', models.DateTimeField(blank=True, help_text='This is the date that the sensor actually took the reading.', null=True)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='sensorreading',
            index_together=set([('longitude', 'latitude')]),
        ),
    ]
