# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_auto_20161018_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibratedreading',
            name='unit_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='unit_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
