# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 19:37
from __future__ import unicode_literals

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='api_key',
            field=accounts.models.ApiField(blank=True, default=None, max_length=256, null=True, unique=True),
        ),
    ]
