# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='deployment',
        ),
        migrations.AddField(
            model_name='device',
            name='deployments',
            field=models.ManyToManyField(related_name='device_deployments', to='deployments.Deployment'),
        ),
    ]
