# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0003_auto_20161004_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
