# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('version', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('version', models.CharField(blank=True, max_length=1000, null=True)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'TEMPERATURE'), (2, 'HUMIDITY'), (3, 'PRESSURE'), (4, 'PM2.5'), (5, 'PM10'), (6, 'Ozone'), (7, 'CO'), (8, 'SO2'), (9, 'NO2'), (9, 'NO2')], db_index=True, default=0, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='platform',
            name='sensors',
            field=models.ManyToManyField(to='platforms.Sensor'),
        ),
    ]
